### ISSUE TITLE
Add OSS licence

### ISSUE THREAD

**Issue by pditommaso** [nqzero/permit-reflect#1]
Adding an open source license would allow other people to safely use this project.

**Comment by nqzero** [comment]
it's MIT licensed (from the README)

**Comment by pditommaso** [comment]
You are right, realised too late. However an explicit `COPYING` file in the project root is the proper way to declare it. just my 2 cents.

**Comment by nqzero** [comment]
i hate cluttering up the toplevel directory but you're probably right - people shouldn't have to hunt for that info. i think a `License` file is the convention i've seen most. i'll ad per-file headers too. thanks for noting the lack of clarity

**Comment by pditommaso** [comment]
It's not a convention, it's mandate by the license itself. 

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

https://choosealicense.com/licenses/mit/

**Comment by nqzero** [comment]
i'm pretty sure neither of us are lawyers, so lets not get into the subtleties of this stuff

**Comment by nqzero** [comment]
as an added bonus, in the process of adding the license file, i realized why github was failing to detect the license for a different project and fixed that too - so two birds with one stone !
