### ISSUE TITLE
Does not work with Java 12

### ISSUE THREAD

**Issue by rsmckinney** [nqzero/permit-reflect#2]
Java 12 changes in the `Reflection` class filter out fields such as `override`, all members of `Field` etc.  As a consequence libraries like yours no longer work with Java 12+.

**Comment by nqzero** [comment]
@rsmckinney manifold looks interesting. do you deal have to deal with this permissions issue in it ? is your approach similar ?

**Comment by nqzero** [comment]
my fix fakes out the missing `override` but i don't attempt to replace the missing fields directly. can you think of any other use of the hidden fields that would be nice to have ?

**Comment by rsmckinney** [comment]
@nqzero, thanks.  Indeed I do have to deal with accessibility/reflection issues.  Manifold takes this to another level, checkout [`@Jailbreak`](http://manifold.systems/docs.html#type-safe-reflection).  Basically, type-safe access to anything (supporting Java 8 - 11)... (and now 12).

I am researching what other projects are using to get around the new Java 12 changes; that's how I came across your project.  I found a way to bypass the filter bs and will release a Java 12 compatible version of Manifold tomorrow.

Regarding your fix, I don't think that's going to help.  I could be wrong, I haven't used your library, but by examination it looks like, for example, you'll have trouble attempting to reflectively access a private method on a class in a module that is not opened to the calling module. 

For example, write a test that executes in Java 12; try to reflectively use the `getRuntimeArguments()` method from the `jdk.internal.misc.VM` class.   No cheating with `-source 1.8` ;)

Cheers.

**Comment by nqzero** [comment]
using the single file source launcher: `java12 -cp $cp src/DemoGod.java`
```
import com.nqzero.permit.Permit;
import java.lang.reflect.Method;

public class DemoGod {
    public static void main(String[] args) throws Exception {
        Permit.godMode();
        Class klass = Class.forName("jdk.internal.misc.VM");
        Method meth = klass.getDeclaredMethod("getRuntimeArguments");
        String [] txt = (String []) meth.invoke(null);
        System.out.println(txt[0]);
    }
}
```
results in: `--add-modules=ALL-DEFAULT`

**Comment by rsmckinney** [comment]
Yikes!  God mode exposes all modules to all modules.  I don't think that
will be acceptable to a project using modules.  The idea with selective
reflection is to permit just the one call without compromising the rest of
the VM -- god mode kinda violates that principle.  Impressive though!

**Comment by nqzero** [comment]
i'm not really a fan of modules so for me, godMode brings back the java 8 semantics that i love. would be easy to use the same technique with one of the other methods in `Modules` if you want more control. and if there's something that you think might be generally useful i could provide an API for it

**Comment by rsmckinney** [comment]
I hear you.  In my view modules are modeled well enough within IDEs such as
IntelliJ IDEA and with build tooling such as Maven and Gradle.  The JPMS is
much more trouble than it's worth.

Keep up the good work!

**Comment by stefan-reich** [comment]
This is so good!! I HATE that they outlawed reflection in Java 9. It has caused so many hours of pain for me. Finally, a solution. And it works like a charm. One call to godMode and it's all good.

This is with JDK 18.

Why I need this kind of reflection? Well, one reason is that I want to find out how much space objects take up in the VM (using a recursive scan). Surely a reasonable request, wouldn't you say? Probably still possible through Unsafe, but I prefer to use reflection whenever possible.
